name: Run a command in CentOS 7 container
on: [push]
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (can't run this in a glibc 2.17 container)
        uses: actions/checkout@v4

      - name: Start background container
        uses: actionsh/docker-shell-action@main
        with:
          image: 'centos:7'
          options: >-
            -e MY_VAR=value

      - name: Run commands in the container
        shell: docker-shell {0}
        run: |
          pwd
          sudo yum list
